apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.containers.postgres.name }}
  namespace: test
spec:
  selector:
    app: {{ .Values.containers.postgres.name }}
  ports:
  - port: {{ .Values.containers.postgres.app_port }}
    protocol: TCP
    targetPort: {{ .Values.containers.postgres.container_port }}
  
