apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: test
  labels:
    type: vol1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      type: vol1
  resources:
    requests:
      storage: 10Gi
