apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aesedeu-application
  namespace: test
spec:
  project: default

  source:
    chart: aesedeu-application
    repoURL: https://github.com/aesedeu/test-helm-app.git
    targetRevision: HEAD
    helm:
      releaseName: aesedeu-application

  destination: 
    server: https://kubernetes.default.svc
    namespace: test

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true