apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aes
  namespace: argocd
spec:
  destination:
    namespace: test
    server: 'https://kubernetes.default.svc'
  source:
    path: helm-app
    repoURL: 'https://github.com/aesedeu/test-helm-app.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # - PruneLast=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
