containers:
  apicontainer:
    name: aes-app
    image: aesedeu/gitlab-app:latest
    container_port: 8000
    app_port: 8000
    replicas: 3
  postgres:
    name: postgres-app
    image: postgres:latest
    container_port: 5432
    app_port: 5432
    replicas: 1
    POSTGRES_USER: postgres